### ISSUE TITLE
adding TClonesArray data in histograms in THaOutput

### ISSUE THREAD

**Issue by rwmichaels** [JeffersonLab/analyzer#120]
The Hall C guys may have been too shy to mention this, but they recently spotted a problem that 2D histograms involving TClonesArrays (like plotting H.hod.1x.posadcpad on the X axis and H.hod.1x.posadcval on the Y axis) ... look like junk.  It looks like THaOutput chokes on this.  I think the solution is to first check if the variable is a TClonesArray; if not, do the same as before, and if it is, use the "GetData" method to obtain the data for the output.  I am not sure how to do this yet, but I'll work on it.  It seems that pretty much all the data that hall C tries to add to the output is a TClonesArray, so this should be a generally useful fix.

**Comment by hansenjo** [comment]
Before you spend any time of this, let me check if I haven't already solved this problem. I have a much-modified version of THaOutput in my development directory. I'll check it by Monday.

Ole

**Comment by hansenjo** [comment]
Just to clarify: Does this problem only affect 2D histograms that are defined in the output definition file of THaOutput? I.e. histograms that are filled within THaOutput and written directly to the ROOT file as histogram objects? So the problem is with the 2D histogram filling functionality within THaOutput?

If I define individual variables on TClonesArrays, write those to the output tree, and then open the output file and plot them against one another with T-Draw(), there is no problem whatsoever.

**Comment by hansenjo** [comment]
I can confirm that I get somewhat different results between a 2D histogram defined via THaOutput and a 2D plot made with T->Draw() projected into a temporary histogram. Now chasing the bug ...

**Comment by rwmichaels** [comment]
Or you can let me take care of it, since I was the original author.  But then I'd need to have the 
latest version of THaOutput, which is in your development version.  

The rules for 2D histograms are a little tricky (but documented).  One is trying to decide based on the
dimensionality of the quantities being plotted whether to put everything into one histogram, or to expand 
into a "vector" of histograms, which is sometimes useful.  I think that for this problem, the solution
is to add a new recognition that if the axes are TClonesArrays with "Get" methods that need to be used,
then use those methods.  The methods seem to be passed as part of the global variables, so I think they 
are available to THaOutput.

E.g. Hall C plots ADC values versus a paddle number.  It seems that nearly 100% of what Hall C plots is
from TClonesArrays, so solving this will be a big help.

Bob

----- Original Message -----
