### ISSUE TITLE
Proposed Modifications to THaOutput and THaVhist to support Hall C

### ISSUE THREAD

**Issue by rwmichaels** [JeffersonLab/analyzer#129]
Dear Eric Pooser:

As I understand it you want the following two modifications to
the Podd THaOutput capability.  Let me know if I've got this right.

1. A 2D histogram is defined

  TH2F Hxy 'title' Vec1 Vec2 nbinx xlo xhi nbiny ylo yhi [Cut]

where Cut is an optional cut, and is either a single (scalar) cut 
or a vector of cuts whose indices track that of Vec1, Vec2.

What you want is that all this goes into one 2D histogram. 

Present behavior: Hxy expands into a vector of histgrams 
     Hxy0, Hxy1, Hxy2, Hxy3 ...
with dimension of the Vec1 (Vec1 & Vec2 must have same dimensions).

Why we do that, I explain in the Appendix.

For the fix, I propose to define new types

   vTH2F  -- which does the Present behavior
   sTH2F  -- scalar histogram -- what you want
 
and keep TH2F behavior the same as before for backward compatibility, 
but print a warning. (A TH2F resolves to either a scalar or a vector
depending on some published rules.) And same for TH1F, TH1D, TH2D.  

As for the implementation, I think that in THaVhist::Process for the
sTH2F, "IsScalar" is true and it processes like it does now, except that
if the Cut is a vector it has to use the index of the Cut.  And the
vTH2F will be the same as before.  BTW, I misspelled scalar everywhere 
(always struggling with "scaler" in DAQ)

2. You want the "eye" histograms to have an optional offset.

  TH2F a1 phgcerEye 'SHMS Heavy Gas Cherenkov' [I] P.hgcer.goodAdcPed 6 -1.5 4.5 1000 0 10000

  right now this will plot Y-axis vs X-axis as follows:

     P.hgcer.goodAdcPed[0]  vs 0
     P.hgcer.goodAdcPed[1]  vs 1
     P.hgcer.goodAdcPed[2]  vs 2
     P.hgcer.goodAdcPed[3]  vs 3
       (etc)

  You simply want the option to skip indices (because your arrays don't start at 0).

  I propose a optional notation as follows (and note the "[I+2]" instead 
      of "[I]" and it will be case insensitive, [I] or [i] )

  TH2F a1 phgcerEye 'SHMS Heavy Gas Cherenkov' [I+2] P.hgcer.goodAdcPed 6 0 6 1000 0 10000

  This will plot

     P.hgcer.goodAdcPed[2]  vs 2
     P.hgcer.goodAdcPed[3]  vs 3
     P.hgcer.goodAdcPed[4]  vs 4
       (etc, up to the dimension of the array)

  As for implementation, I believe this offset can be propagated to THaVhist::Process and 
  become an offset to a loop that fills the histogram.

  Appendix
  ========

  Whey do we have vectors of histograms ?   In hall A we use lines like 
  this in our output definition file.  Admittedly mostly for 1D histograms.

  TH1F Rs0ra 'Right arm S0 ADC' R.s0.ra 2000 0 2000 R.s0.ra>0.

  TH1F Lsha 'PionRejector ADCs' L.prl2.a 2000 0.5 2000.5 L.prl2.a>0.

  which expand into vectors of histograms (e.g. 128 histograms for
  the shower detector).  In retrospect, adding "s" or "v" at the
  start of the name (vTH1F  or  sTH1F) would be less ambiguous.

**Comment by pooser** [comment]
@rwmichaels,

In regards to point 2, we do not want so skip indices.  We would like to offset the indices.  For example, instead of plotting the following:

 P.hgcer.goodAdcPed[0]  vs 0
 P.hgcer.goodAdcPed[1]  vs 1
 P.hgcer.goodAdcPed[2]  vs 2
 P.hgcer.goodAdcPed[3]  vs 3

we would like to plot:

 P.hgcer.goodAdcPed[0]  vs 1
 P.hgcer.goodAdcPed[1]  vs 2
 P.hgcer.goodAdcPed[2]  vs 3
 P.hgcer.goodAdcPed[3]  vs 4

The functionality you mentioned may prove to be useful in the future.  I do not see the harm in implementing that as well while we are on the topic.

**Comment by rwmichaels** [comment]
Here is an output definition file, which works in my hallc_replay area.  It illustrates the changes I made and what is coming.  The next steps in this project are to analyze some old data and verify that nothing got "broken".  Then I will push it to my repository and let Eric check it.  The hall C data look ok from my POV, but I'm not so familiar with those data to be sure.

# Output definition file illustrating modifications for Hall C

# The "eye" stuff

# This plots P.hgcer.goodAdcPed versus its index [I] starting at I=0 (old behavior)
TH2F phgcerEye1 'SHMS Cherenkov eye' [I] P.hgcer.goodAdcPed 6 -1.5 4.5 1000 0 10000

# This plots P.hgcer.goodAdcPed[0] vs 1, P.hgcer.goodAdcPed[1] vs 2, P.hgcer.goodAdcPed[2] vs 3, etc 
# [I+1] will add 1 to the index I on the X-axis, but the array still starts at 0
TH2F phgcerEye2 'SHMS Cherenkov eye+1' [I+1] P.hgcer.goodAdcPed 6 -1.5 4.5 1000 0 10000

# Offset the index by 452.  (it's a silly demo that it works)
TH2F phgcerEye3 'SHMS Cherenkov eye+2' [I+452] P.hgcer.goodAdcPed 40 440 480 1000 0 10000

# Vectors and scalar histograms

# The original title the following several histograms was
# 'SHMS Heavy Gas Cherenkov Good Pulse Pedestal vs. Counter Number; Counter Number; Good Pulse Pedestal / 10 ADC Units' 
# but I changed those to explain the tests

# For scalar histograms, note the leading "s" in the type, e.g. sth2f (case insensitive)
sTH2F phgcerScalar0 'Scaler Histogram with no cut' P.hgcer.numGoodAdcHits P.hgcer.goodAdcPed 4 0.5 4.5 1000 0 10000

sTH2F phgcerScalar1 'Scalar histogram with a vector cut, the indices track' P.hgcer.numGoodAdcHits P.hgcer.goodAdcPed 4 0.5 4.5 1000 0 10000 P.hgcer.numGoodAdcHits>0

sth2f phgcerScalar2 'Scalar histogram with with scalar cut' P.hgcer.numGoodAdcHits P.hgcer.goodAdcPed 4 0.5 4.5 1000 0 10000 P.hgcer.numGoodAdcHits[0]>0

# The following produces vector of histograms phgcerVectA0, phgcerVectA1, phgcerVectA2, etc.  Note the leading "v" in "vth2f" (case insenstive).  Also you get this behavior if you leave off the "v".
vth2f phgcerVectA 'Vector of histograms' P.hgcer.numGoodAdcHits P.hgcer.goodAdcPed 4 0.5 4.5 1000 0 10000 P.hgcer.numGoodAdcHits>0

# Another vector histogram (what Hall C does NOT want).  you get the A0, A1, A2 ... vector
TH2F phgcer_goodpi_vs_goodptimeA 'SHMS Heavy Gas Cherenkov Good Pulse Integral vs. Good Pulse Time; Good Pulse Integral; Good Pulse Time' P.hgcer.goodAdcPulseInt P.hgcer.goodAdcPulseTime 4000 0 40000 1000 0 10000

# A scalar histogram (what hall C wants).  Only diff is the leading "s" in sTH2F.  Only 1 histogram shows up.
sTH2F phgcer_goodpi_vs_goodptimeB 'SHMS Heavy Gas Cherenkov Good Pulse Integral vs. Good Pulse Time; Good Pulse Integral; Good Pulse Time' P.hgcer.goodAdcPulseInt P.hgcer.goodAdcPulseTime 4000 0 40000 1000 0 10000

# Same scalar histogram as above, but with a cut, the indices of the cut track the indices of the variables being plotted
sTH2F phgcer_goodpi_vs_goodptimeC 'SHMS Heavy Gas Cherenkov Good Pulse Integral vs. Good Pulse Time; Good Pulse Integral; Good Pulse Time' P.hgcer.goodAdcPulseInt P.hgcer.goodAdcPulseTime 4000 0 40000 1000 0 10000  P.hgcer.goodAdcPulseInt>0

**Comment by rwmichaels** [comment]
As explained in the https://github.com/JeffersonLab/analyzer/issues/129
the attached output definition file explains the new capabilities that
were implemented in the output class for Podd.  I still need to verify
carefully that nothing "broke" on old data -- by doing the "all bins
identical" tests.  But it's looking pretty good.  You can tell me if
I'm on the right track here.

I think I can finish this by Friday.

yours

Bob

**Comment by hansenjo** [comment]
A good illustration of why we need a regression test suite for the
analyzer. If we already had one, all you'd have to do was "make check"
to test if anything was "broken" by these changes.

Ole

**Comment by rwmichaels** [comment]
Today I've committed and pushed the changes for THaOutput, THaVhist, and THaVform
to my git repo in the branch "OutputForHallC".  It is ready for a pull request, but
Eric Pooser and I agreed it would be a good idea for him to take a look at the changes
first and test to see if they satisfy the needs.  More changes might be needed.

   https://github.com/rwmichaels/analyzer/tree/OutputForHallC

The output def file is, as explained in the issue tracker, for example:
cdaq@cdaql1:/net/cdaqfs/home/cdaq/bob/vec-histo-work/hallc_replay/DEF-files/SHMS/HGCER/
phgcerana.def

My tests: I ran the code in the hall C environment on some hall C data, and also
I ran it on some hall A data (PREX and Transversity) to verify that "all bins 
are identical".  I'm comparing to the version with Ole's bugfix from Jan 23, 2017.  
The comparison script was put into ./util/comp_histo.C and is self-explanatory.

Bob

**Comment by pooser** [comment]
I pulled down Bob's branch and ran it over some Spring 2017 data.  As far as I can tell the behavior is as exactly as we requested and as Bob has outlined in the above comments.

In my opinion these new features are ready to be merged into the master branch.

These new features are excellent!  Thank you for your time and efforts regarding this matter Bob.

**Comment by hansenjo** [comment]
Sounds great. Thanks Bob & Eric.

Bob, could you make a pull request? I don't see any of this new code on
GitHub yet.

Ole

**Comment by hansenjo** [comment]
Closed with pull request #130
