### ISSUE TITLE
Hall C Message while running analyzer: svPrefix histogram type = block histtype length 5

### ISSUE THREAD

**Issue by Yero1990** [JeffersonLab/analyzer#133]
While running the Hall C Analyzer, the message: "svPrefix histogram type = block histtype length 5" appeared for each histogram I defined in the def file. I tracked where it was coming from, and it seems it
is from the podd source code THaOutput.C, where the message is outputted if a certaing debug statement is true.

@rwmichaels

**Comment by pooser** [comment]
@rwmichaels This minor issue is still present.  It pollutes the output of the analyzer.  Is this an easy fix?

**Comment by rwmichaels** [comment]
Yes, easy.  Set ldebug=0 in THaOutput::svPrefix.  Done and pull-requested.

----- Original Message -----

**Comment by pooser** [comment]
Whew, I did not intend for you too have to do so much heavy lifting today! :-p  Thanks Bob!

**Comment by hansenjo** [comment]
Resolved by commit 065045ae8202823084005d674506bd0e9086d1f5
