### ISSUE TITLE
SCons build with standalone=1 links duplicate objects

### ISSUE THREAD

**Issue by hansenjo** [JeffersonLab/analyzer#142]
The SCons build with standalone=1 creates and links two copies of the compiled hana_decode objects.

First, the decoder shared library libdc.so is built from *.os objects. A few example lines, highlighting the Lecroy1877Module:
```
c++ -o hana_decode/Lecroy1877Module.os -c -g -O0 -Wall -Woverloaded-virtual -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -std=c++11 -m64 -pthread -rdynamic -fPIC -DWITH_DEBUG -DLINUXVERS -DHAS_SSTREAM -I/home/ole/evio-4.4.6/Linux-x86_64/include -Isrc -Ihana_decode -I/usr/include/root hana_decode/Lecroy1877Module.C

c++ -o libdc.so.1.6.0 -pthread -shared .... hana_decode/Lecroy1877Module.os .... hana_decode/THaDecDict.so -L/usr/lib64/root -L. -L/home/ole/evio-4.4.6/Linux-x86_64/lib -Lsrc -Lhana_decode
```

Second, the sources are compiled again, this time into objects with suffix *.o:
```
c++ -o hana_decode/Lecroy1877Module.o -c -g -O0 -Wall -Woverloaded-virtual -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -std=c++11 -m64 -pthread -rdynamic -DWITH_DEBUG -DLINUXVERS -DHAS_SSTREAM -I/home/ole/evio-4.4.6/Linux-x86_64/include -Isrc -Ihana_decode -I/usr/include/root hana_decode/Lecroy1877Module.C
```

Those objects are then used to build the standalone executables:
```
c++ -o hana_decode/tstfadc_main.o -c -g -O0 -Wall -Woverloaded-virtual -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -std=c++11 -m64 -pthread -rdynamic -DWITH_DEBUG -DLINUXVERS -DHAS_SSTREAM -I/home/ole/evio-4.4.6/Linux-x86_64/include -Isrc -Ihana_decode -I/usr/include/root hana_decode/tstfadc_main.C
c++ -o hana_decode/tstfadc -pthread .... hana_decode/Lecroy1877Module.o .... hana_decode/tstfadc_main.o hana_decode/THaDecDict.so -L/usr/lib64/root -L. -L/home/ole/evio-4.4.6/Linux-x86_64/lib -Lsrc -Lhana_decode -lHallA -ldc -levio -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lm -ldl
Install file: "hana_decode/tstfadc" as "bin/tstfadc"
```
but those executables are also dynamically linked to libdc.so, do the same objects appear twice at runtime. This causes various breakage (attempt to register modules twice, double free on exit) when running these executables.

The make build is unaffected.

**Comment by brash99** [comment]
OK, I think that I have fixed this one.  There was a bug in hana_decode/SConscript.py.  I also have added a “clean” feature so that the standalone executables are removed when one does “scans -c”.

I tested that the standalone executables all get built and installed correctly, at least.

Here is a link to the commit that includes these changes … Ole, can you just grab these changes from here?  

24ff139 <https://github.com/brash99/analyzer/commit/24ff139edf62e1d338dece048a5fb62e2bd93cc2>

Cheers,
E.

**Comment by hansenjo** [comment]
Hi Ed,

thanks for the quick fix. Looking at the commit you linked, I was just
wondering why hana_decode/haDecode_LinkDef.h was removed. Hopefully this
doesn't happen as part of the updated "clean" feature  ...

Ole

**Comment by brash99** [comment]
Hi Ole,

Sorry … no, that should not be in there.  This was a remnant of other work that I was doing on this branch having to do with getting rid of this file, and generating automagically (as is done for the hcana linkdef file).

Cheers,
E.
