### ISSUE TITLE
data_type_def not necessarily defined here

### ISSUE THREAD

**Issue by sawjlab** [JeffersonLab/analyzer#151]
https://github.com/JeffersonLab/analyzer/blob/63ee549ae5a12e690792bdf20d18c8a0ab7f78a8/hana_decode/PipeliningModule.C#L79

**Comment by hansenjo** [comment]
Oh - why is the codabuffer passed into SplitBuffer by value and not as a const reference? The whole buffer is copied every time this function is called ...

The same happens every time the buffer is pushed into "eventblock":
```c++
eventblock.push_back(codabuffer);
```
Please think of a way to avoid all this copying. Can we work with pointers instead?

**Comment by rwmichaels** [comment]
It probably doesn't need to be static.  I'll need to study the code to be sure, and today I'm extremely busy (I'm one of two people on shift).  As for why to copy the buffer each time, I think it happens only in MULTIBLOCK mode, and only when you get to a new block.  Typically MULTIBLOCK=100 so it would only happen every 100 events.  I need to check to make sure of that, though.  But yeah, maybe it can be done better. 

BTW, MULTIBLOCK mode does not work for Fastbus data yet.  (relevant to SBS).  The Fastbus data look ok but the decoder cannot split the blocks yet.  Not a problem in principle, just some grungy programming that needs to be done for SBS.

Bob

----- Original Message -----

**Comment by sawjlab** [comment]
There is no rush to do anything from the hcana point of view.  The uninitialized variable is just something I noticed while using the FADC code as a guide to writing a decoder for TI data.  It won't affect Hall C right now as we don't use multiblock.  (Removing static from the definition of data_type_def will probably allow the compiler to flag this as a problem.)

I think Ole is right about the copying.  Even in non-multiblock, codabuffer is copied twice per event.  So reducing the copying will help performance, but we need to make sure not to break FADC decoding.

**Comment by rwmichaels** [comment]
Hall C would be doing a service to the "Podd" community to run 10 or 20 min with multiblock mode,
then we can analyze the data and verify the decoding works reliably -- including the TI data and
whatever other devices you have (CAEN ADCs ?) -- and also check the performance issues (copying 
unecessarily, etc).  I had some multiblock mode data from test setups, but there's nothing like
real experiment data.

The DAQ can get a good improvement from running in buffering mode.  This does not affect the event
structure, so it should work right away for the decoder (there may be other reasons to avoid it,
though).  Multiblock mode is an alternative way to get better DAQ performance.  And combining them 
(buffering plus multiblock) should yield the ultimate performance.  So, it would be good to get
some data in 3 modes: 1) buffering only, 2) multiblock only, and 3) combined buffering and multiblock.

Bob

----- Original Message -----

**Comment by hansenjo** [comment]
Moved to Redmine [issue 265](https://redmine.jlab.org/issues/265)
