### ISSUE TITLE
Cmake generator expressions

### ISSUE THREAD

**Issue by whit2333** [JeffersonLab/analyzer#171]
https://github.com/JeffersonLab/analyzer/blob/83ee64e5a049289eedf428a323d22d12b58fb3f8/src/CMakeLists.txt#L80

Any build logic can be handled by cmake's generator expressions. https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html

**Comment by hansenjo** [comment]
Whit, look, there are really more important things to work on. This is not a bug, it's at best a question of style, probably more or less just trolling on your part. If the way it is done causes you a specific problem, please report it with details on the environment and how to reproduce it. I will close any further "issues" that relate merely to style and opinion.
