### ISSUE TITLE
Docker Container for Hall A analyzer.

### ISSUE THREAD

**Issue by panta-123** [JeffersonLab/analyzer#188]
The idea is to create docker container for Hall A anlyzer. The container creation will be done automatically via github action. 
For each tag created in the repo, action will be triggered and the docker image will be registered to jefferson lab docker hub.
Example docker created in the test is at : 
https://hub.docker.com/r/apanta123/hallaana

Firstly the container will be build on centos7 (with platorm arm64 and amd64) . If any other OS is needed it can be done.

**Comment by hansenjo** [comment]
Merged corresponding pull request in commit 170e466eae53965d709eaba8c7311cbfb65f14b8.
