### ISSUE TITLE
Reorganization of src, hana_scaler, and hana_decode directories

### ISSUE THREAD

**Issue by brash99** [JeffersonLab/analyzer#28]
It would be nice if only the pieces of code (*.h and *.C) files that are actually needed for building the analyzer were located in these directories, so that wildcards could be used in the build files (either Makefiles or SConstruct/SConscripts).  One could possibly move the pieces required for building standalone codes to another parallel directory, or to a and appropriate subdirectory.

**Comment by hansenjo** [comment]
Moved to Redmine [issue/feature 46](https://redmine.jlab.org/issues/46)
