### ISSUE TITLE
Timezone differences with recent ROOT version

### ISSUE THREAD

**Issue by carlosmunozcamacho** [JeffersonLab/analyzer#34]
When using analyzer 1.5.22 against recent ROOT version 5.34, and replaying a CODA file in a different time zone (French time in my case), the run time is not correctly identified (by correctly I mean EST time, in which the db_run.dat file is usually written). This obviously messes up the reconstruction... This didn't happen with ROOT version 5.18.

I show screen outputs for the same run, with different ROOT version below. Could someone confirm this ?

Thanks,
Carlos

---
-                                              *
-            W E L C O M E  to  the            *
-       H A L L A   C++  A N A L Y Z E R       *
-                                              *
-        Release     1.5.22        Nov  7 2013 *
-  Based on ROOT  5.34/11          Oct 31 2013 *
-                                              *
-            For information visit             *
-        http://hallaweb.jlab.org/root/        *
-                                              *
  ************************************************

CINT/ROOT C/C++ Interpreter version 5.18.00, July 2, 2010
Type ? for help. Commands must be C++ statements.
Enclose multiple statements between { }.

Processing ProcessRun.C...

The target is Hydrogen 15cm

Will analyze file ./dvcs10_9639.dat.0
Opening file ./dvcs10_9639.dat.0
TCaloEvent constructor
Creating new output file: ./dvcs_9639_0.root
Prestart at 1
Prescales at 2
THaRunParameters::ReadDatabase: Opened database file /afs/in2p3.fr/home/throng/clas/carlos/DVCS2/onlana/DB2/db_run.dat
OBJ: THaRun     RUN_9639
Run number: 9639
Run date:   Tue Dec 14 21:22:41 2010

However:

---
-                                              *
-            W E L C O M E  to  the            *
-       H A L L A   C++  A N A L Y Z E R       *
-                                              *
-        Release     1.5.22        Nov 20 2013 *
-  Based on ROOT  5.18/00          Jan 16 2008 *
-                                              *
-            For information visit             *
-        http://hallaweb.jlab.org/root/        *
-                                              *
  ************************************************

CINT/ROOT C/C++ Interpreter version 5.16.29, Jan 08, 2008
Type ? for help. Commands must be C++ statements.
Enclose multiple statements between { }.

Processing ProcessRun.C...

The target is Hydrogen 15cm

Will analyze file ./dvcs10_9639.dat.0
Opening file ./dvcs10_9639.dat.0
TCaloEvent constructor
Creating new output file: ./dvcs_9639_0.root
Prestart at 1
Prescales at 2
THaRunParameters::ReadDatabase: Opened database file /afs/in2p3.fr/home/throng/clas/carlos/DVCS2/onlana/DB2/db_run.dat
OBJ: THaRun     RUN_9639
Run number: 9639
Run date:   Tue Dec 14 15:22:41 2010

**Comment by hansenjo** [comment]
Moved to Redmine [issue/bug 62](https://redmine.jlab.org/issues/62)
