### ISSUE TITLE
proposed removal of /hana_scaler and a few other things

### ISSUE THREAD

**Issue by rwmichaels** [JeffersonLab/analyzer#69]
After the dust clears a bit on the recent changes, and if the event handler scheme is accepted, I'd like to propose to remove the /hana_scaler directory and "all things related to scalers" in /src, except for the scaler event handler.  This will remove about 7K lines of unneeded code.  Such a large cleanup may seem surprising, but the reasons are 1) we don't need the scaler GUI in Podd, 2) database handling is simplified -- handled now by THaAnalysisObject base class of event handlers, and 3) all the standalone tscal*_main.C codes can be replaced by variants of the scaler event handler plug-in; besides, I don't think anyone used them except me.

In addition to the above, I would remove  THaCodaDecoder and THaFastBusWord.

**Comment by hansenjo** [comment]
Sounds good to me. Thanks to git, we can always restore this code in
case we later find it still has some use.

Ole

**Comment by rwmichaels** [comment]
With my branch "cleanScaler" this issue has been addressed, and a pull request was made.  Closed for now.
