### ISSUE TITLE
Duplicated branch with formula in odef file

### ISSUE THREAD

**Issue by xulongwu4** [JeffersonLab/analyzer#83]
When using the formula (and it probably also happens to cut, although I didn't test it) in odef file, duplicated branches with the same name as the formula name are produced in the T tree. For example, if I have the following line in the odef file:

FORMULA urbax 1000.*Lurb.BPMA.x

Two branches with the same name urbax are generated in the T tree. This can be seen if one does "T->Print()" and checks the printed message.

This is usually fine, but complaints are seen when one tries to do something like "T->MakeClass()". This issue happens to both analyzer 1.5 and 1.6

**Comment by hansenjo** [comment]
Thanks for the report. Confirmed the problem and working on a fix.
